# Generated by Django 5.1.dev20231006075245 on 2023-10-10 15:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dustbins',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'dustbins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodAreas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'food_areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodStalls',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'food_stalls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoPoints',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'info_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KidsArena',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'kids_arena',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'shops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Souvenirs',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'souvenirs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('genre', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'stages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrampolinePark',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'trampoline_park',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Washrooms',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'washrooms',
                'managed': False,
            },
        ),
    ]
